pad_axis_deadzone=16000
input.a=sdl:122
pad.a=button:a
input.b=sdl:120
pad.b=button:b
input.select=sdl:8
pad.select=button:back
input.start=sdl:13
pad.start=button:start
input.right=sdl:1073741903
pad.right=button:dpad_right
input.left=sdl:1073741904
pad.left=button:dpad_left
input.up=sdl:1073741906
pad.up=button:dpad_up
input.down=sdl:1073741905
pad.down=button:dpad_down
